### PR TITLE
Update droidmedia to 0.20240322.0 (as for sailfishos 4.6)

### PR DESCRIPTION
**Pull request by piggz**

### CODE REVIEW

**Comment by peat-psuwit** [comment]
This release seems to contain ABI break from Android-library side.

https://github.com/sailfishos/droidmedia/commit/00a460b96ba54be4b6c00b13bcde91297c43d8b6

Distributions (e.g. UBports) will have to update their copy of headers and rebuild dependent packages.

**Comment by piggz** [comment]
Maybe, though Im sure droidmedia is only used by sailfish.  UBPorts uses a different media pipeline iirc.  Could someone else confirm?

**Comment by FakeShell** [comment]
FuriOS uses droidmedia for v4l2loopback and camera video recording

**Comment by peat-psuwit** [comment]
@piggz indeed, after another look, we used to have an experiment on bringing droidmedia to Ubuntu Touch, but it didn't go well, so we keep using libcamera_compat_layer/libmedia_compat_layer for that.

That said, I think Droidian uses Halium. @erfanoabdi could you please maybe confirm if Droidian uses droidmedia or not?

**Comment by erfanoabdi** [comment]
> That said, I think Droidian uses Halium. @erfanoabdi could you please maybe confirm if Droidian uses droidmedia or not?

yeah droidian is using droidmedia as well, we should update packages accordingly

**Comment by piggz** [comment]
So, we're generally in agreement to upgrade the image?

**Pull request merged**
